management:
  server.port: 33333
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.health.show-details: never
  health:
    defaults.enabled: false
    db.enabled: false
  info.git.mode: full

server.port: ${management.server.port}

spring:
  main:
    banner-mode: "OFF"
  application.name: Spider4VideoStation
  boot.admin.client:
    enabled: false
    url: http://localhost:25020
    instance.prefer-ip: true
    auto-deregistration: true

logging:
  file: logs/spider4videostation.log
  file.max-history: 30
  level:
    root: info

webDriverAddr: http://127.0.0.1:4444
webDriverArgs:
#- "--headless"
- "--disable-gpu"
- "--disable-extensions"
- "--disable-browser-side-navigation"
- "--disable-dev-shm-usage"
- "--blink-settings=imagesEnabled=false"
- "--no-sandbox"
- "--start-maximized"
- "--enable-automation"
webDriverSearcherTimeoutMillis: 30000
webDriverStaticerTimeoutMillis: 30000

staticWebDriverArgs:
- "--disable-gpu"
- "--disable-extensions"
- "--disable-browser-side-navigation"
- "--disable-dev-shm-usage"
- "--disable-web-security"
- "--no-sandbox"
- "--start-maximized"
- "--enable-automation"
staticMode: xhrSync
staticLoadTimeoutMillis: 60000
staticChromeDownloadFolder: /home/seluser/Downloads

cacheMaxSize: 1073741824
cacheExpireDuration: 2592000000  

javdbOrigin: https://javdb36.com
javdbTouchUrl: ${javdbOrigin}/manifest.json
javdbTimeoutMillis: 30000

doubanDomain: douban.com
doubanOrigin: https://${doubanDomain}
doubanTouchUrl: ${doubanOrigin}/robots.txt
doubanSearchDomain: search.${doubanDomain}
doubanSearchMovieUrl: https://${doubanSearchDomain}/movie/subject_search
doubanMovieDomain: movie.${doubanDomain}
doubanMovieOrigin: https://${doubanMovieDomain}
doubanMovieItemPatterm: https://${doubanMovieDomain}/subject
doubanLoginWaitTimeoutMillis: 60000
doubanLoginCheckableDomain:
- ${doubanSearchDomain}
- ${doubanMovieDomain}
doubanLoginCheckUrl: ${doubanMovieOrigin}
doubanLoginUrl: https://accounts.${doubanDomain}/passport/login
doubanTimeoutMillis: 30000
doubanMaxLimit: 4
